name: Test

on: workflow_dispatch

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 更新评论
        uses: actions/github-script@v5
        with:
          script: |
            // console.log(process.env.BODY); // 这一行绝对不能去掉，否则运行报错，不知道为什么
            // let body = process.env.BODY.replace(/\\n/g, "\n").replace(/\\r/g, "\r");
            let body = "";
            for (let i = 0; i < 130000; i++)
              body += "a";
            console.log(body.length);
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 1001859610,
              body: body
            });
            // console.log(body); // 这一行绝对不能去掉，否则运行报错，不知道为什么
