name: Test

on: workflow_dispatch

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: "find-keke",
              comment_id: 996055496
            })).data.body;
          result-encoding: string
      - run: |
          wget https://raw.githubusercontent.com/plazum/find-keke/master/high-score.py
          ls -alF
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        env:
          COMMENT: ${{ steps.get-comment.outputs.result }}
          PLAYER_NAME: $$t"e's%25t\\|`uname -a`
        run: |
          mkdir .idea
          echo "$COMMENT" > .idea/comment.txt
          echo "| $PLAYER_NAME | 14 | 10 | 0.00 | Thu Jan 01 1970 08:00:00 GMT+0800 (中国标准时间) |" >> .idea/comment.txt
          python high-score.py
          ls -alFR
      - id: get-comment-body
        run: |
          body="$(cat .idea/processed.txt)"
          body="${body//'%'/'&#37;'}"
          body="${body//$'\n'/'\n'}"
          body="${body//$'\r'/'\r'}"
          echo "::set-output name=body::$body"
      - name: 更新评论
        uses: actions/github-script@v5
        env:
          BODY: ${{ steps.get-comment-body.outputs.body }}
        with:
          script: |
            console.log(process.env.BODY); // 这一行绝对不能去掉，否则运行报错，不知道为什么
            let body = process.env.BODY.replace(/\\n/g, "\n").replace(/\\r/g, "\r");
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 1001859610,
              body: body
            });
            console.log(body); // 这一行绝对不能去掉，否则运行报错，不知道为什么
