name: Test

on: workflow_dispatch

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: return body
        uses: actions/github-script@v5
        id: b
        with:
          result-encoding: string
          script: |
            // console.log(process.env.BODY);
            // let body = process.env.BODY.replace(/\\n/g, "\n").replace(/\\r/g, "\r");
            let body = "";
            for (let i = 0; i < 1024 * 256; i++)
              body += "a";
            console.log(body.length);

            const fs = reqiuire("fs");
            fs.writeFileSync("f.txt", body);
            return "0";

            for (let i = 0; i < 1; i++) {
              for (let j = 0; j < 0; j++)
                body += "a";
              console.log(body.length);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: 1001859610,
                body: body
              });
              console.log(body.length + " OK");
            }
            // console.log(body);
      - name: 更新评论
        uses: actions/github-script@v5
#         env:
#           BODY: ${{ steps.b.outputs.result }}
        with:
          script: |
            // let body = process.env.BODY;
            const fs = reqiuire("fs");
            let body = fs.readFileSync("f.txt");
            console.log(body.length);
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 1001859610,
              body: body
            });
