name: Test

on: workflow_dispatch

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require("fs");
            const body = (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: "find-keke",
              comment_id: 996055496
            })).data.body;
            await io.mkdirP(".idea");
            fs.writeFileSync(".idea/comment.txt", body + "\n");
      - run: |
          wget https://raw.githubusercontent.com/plazum/find-keke/master/high-score.py
          ls -alFR
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        env:
          PLAYER_NAME: $$t"e's&#37;25t\\|`uname -a`
        run: |
          # mkdir .idea
          # echo "$COMMENT" > .idea/comment.txt
          echo "| $PLAYER_NAME | 14 | 10 | 0.00 | Thu Jan 01 1970 08:00:00 GMT+0800 (中国标准时间) |" >> .idea/comment.txt
          cat .idea/comment.txt
          python high-score.py
          ls -alFR
      - name: 更新评论
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require("fs");
            let body = fs.readFileSync(".idea/processed.txt", "utf8");
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 1001859610,
              body: body
            });
