name: Test

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      player_name:
        description: '玩家名'
        required: true
        default: test
      rows:
        description: '行数'
        required: true
        default: '14'
      cols:
        description: '列数'
        required: true
        default: '10'
      score:
        description: '用时'
        required: true
        default: '0.00'
      time:
        description: '时间'
        required: true
        default: Thu Jan 01 1970 08:00:00 GMT+0800 (中国标准时间)

jobs:
  add-a-line:
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment
        uses: actions/github-script@v6
        with:
          script: |
            /*for (let i in github.rest.actions)
              console.log(i);*/
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: "<!-->"
            });
            return;
            const fs = require("fs");
            const body = (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: "find-keke",
              comment_id: 996055496
            })).data.body;
            const line = "| " + context.payload.inputs.player_name
              + " | " + context.payload.inputs.rows
              + " | " + context.payload.inputs.cols
              + " | " + context.payload.inputs.score
              + " | " + context.payload.inputs.time + " |";
            console.log(context.payload.inputs);
            console.log(context.repo);
            console.log(line);
            await io.mkdirP(".idea");
            fs.writeFileSync(".idea/comment.txt", body + "\n" + line);
      # - run: |
      #     wget https://raw.githubusercontent.com/plazum/find-keke/master/high-score.py
      #     ls -alFR
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 生成新评论
        # env:
        #   PLAYER_NAME: ${{ github.event.inputs.player_name }}
        #   ROWS: ${{ github.event.inputs.rows }}
        #   COLS: ${{ github.event.inputs.cols }}
        #   SCORE: ${{ github.event.inputs.score }}
        #   TIME: ${{ github.event.inputs.time }}
        run: |
          # echo "| $PLAYER_NAME | $ROWS | $COLS | $SCORE | $TIME |"
          # echo "| $PLAYER_NAME | $ROWS | $COLS | $SCORE | $TIME |" >> .idea/comment.txt
          # wget https://raw.githubusercontent.com/plazum/find-keke/master/high-score.py
          ls -alFR
          # python high-score.py
          ls -alFR
      - name: 更新评论
        uses: actions/github-script@v6
        with:
          script: |
            /*const fs = require("fs");
            let body = fs.readFileSync(".idea/comment.txt", "utf8").split("\n");
            console.log(body);
            body[0] = body[0].replaceAll(/查看/, "Look");
            console.log(body);
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 1001859610,
              body: body
            });*/
