name: Test

on: workflow_dispatch

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: return body
        uses: actions/github-script@v5
        id: b
        with:
          result-encoding: string
          script: |
            let body = "";
            for (let i = 0; i < 1024 * 124 - 3; i++)
              body += "a";
            console.log(body.length);
            // const fs = require("fs");
            // fs.writeFileSync("f.txt", body);
            return body;

            for (let i = 0; i < 1; i++) {
              for (let j = 0; j < 0; j++)
                body += "a";
              console.log(body.length);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: 1001859610,
                body: body
              });
              console.log(body.length + " OK");
            }
            // console.log(body);
      - name: 更新评论
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: 1001859610
          edit-mode: replace
          body: ${{ steps.b.outputs.result }}
